### DISCUSSION TITLE
Custom HTTP Headers with Client-Side Routing

### DISCUSSION THREAD

**Discussion by picchietti** [static-web-server/static-web-server#213] [Q&A] [answered]
Hi,

I'm using the latest SWS via docker with a toml config file instead of env variables.

SWS is serving my client-side routed (BrowserRouter style) singe page application. It does this through the `page-fallback` option.

I'm trying to set security headers on all client-side routed pages. I would settle for setting the headers on every fetched resource. However, no matter what is set for `source`: `*`, `**`, `*.html`, `**/*`, etc it wont work on routes like `/docs` or `/docs/xyz`. It will work with `/` and `/assets/main.js`. Is there any way I can accomplish this?

Why not use the `security-headers` option? It sets `X-XSS-Protection` which Mozilla says [can cause XSS vulnerabilities](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection), and sets `Strict-Transport-Security` which I don't need to set on my encrypted onion service.

**Comment by joseluisq** [comment]
> However, no matter what is set for `source`: `*`, `**`, `*.html`, `**/*`, etc it wont work on routes like `/docs` or `/docs/xyz`. It will work with `/` and `/assets/main.js`. Is there any way I can accomplish this?

If you want a glob pattern to apply to everything then try an asterisk surrounded by curly braces which will be used as a wildcard.

In the example below, the custom header should be applied to whatever route.

```toml
[advanced]

[[advanced.headers]]
source = "{*}"
# or more advanced one:
# source = "{*/,/*}"
[advanced.headers.headers]
X-Custom-Header = "some-value"
```

**Reply by picchietti** [reply]
I tried both `{*}` and `{*/,/*}`. Unfortuntely, I still saw the same behavior:

No custom header on /docs
![Screenshot from 2023-06-03 16-14-44](https://github.com/static-web-server/static-web-server/assets/1542423/222c433e-ad65-4c33-8567-1960e41f9d79)

Custom header on asset file
![Screenshot from 2023-06-03 16-15-02](https://github.com/static-web-server/static-web-server/assets/1542423/0a48c6af-5032-4118-b7d4-95f0ca73cbc5)

Custom header on /
![Screenshot from 2023-06-03 16-15-17](https://github.com/static-web-server/static-web-server/assets/1542423/85ea1563-b6f6-48c8-9214-389fab1c2b7e)

It seems that it only applies the headers when it doesn't need to `page-fallback`.

To eliminate any weirdness with Tor Browser and hosting through an Onion Service, I hosted it locally and got the same results.

(I am restarting the server each time I change the config.)

This is my toml config:
```toml
[general]

host = "0.0.0.0"
port = 1337
root = "/public"
page-fallback = "/public/index.html"
log-level = "info"
log-remote-address = false
cache-control-headers = true
compression = true
compression-static = false
security-headers = false # set security headers in [advanced] section
cors-allow-origins = ""
cors-allow-headers = ""
directory-listing = false
redirect-trailing-slash = true

[advanced]

[[advanced.headers]]
source = "{*/,/*}"

[advanced.headers.headers]
X-Custom-Header = "some-value"
#Content-Security-Policy = "default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'"
#Permissions-Policy = "geolocation=(), camera=(), microphone=()"
#X-Frame-Options = "DENY"
#X-Content-Type-Options = "nosniff"
```

I've tried it with an without `redirect-trailing-slash`.
I don't see anything in the `trace` logs to note.
I haven't found anything in [globstar](https://docs.rs/globset/0.4.10/globset/) docs yet.

I'm a rust beginner, but I'll do my best to check the source code soonish.
