### DISCUSSION TITLE
How to use config.toml in docker compose?

### DISCUSSION THREAD

**Discussion by carmolim** [static-web-server/static-web-server#277] [Q&A] [answered]
I'm trying to deploy a vue app using static-web-server using docker compose
I need to redirect all the requests to public/index.html

But first need how to correctly pass the `config.toml` to the container, I tried this:

```yaml
  frontend:
    image: joseluisq/static-web-server:2
    ports:
      - 8787:80
    volumes:
      - ./apps/frontend/config.toml:/config.toml
      - ./apps/frontend/dist:/public
```

I know the file has correctly been loaded by the container, but I'm not loading it to the correct path. 

Where I should mount it?

**Comment by joseluisq** [comment, marked as answer]
You just have to tell SWS where to find the config file via  `SERVER_CONFIG_FILE` env. 

The reason is that the config file is optional but there is no a default path for it. Additionally SWS does not check for the config file path at start up (only when it is set).
That's why when you want to use a config file then you have to tell SWS about it explicitly.

We will probably improve this in the future to act like for example the root dir (`./public`).

**Reply by carmolim** [reply]
Thanks, that solved my problem, the final config:
```
  frontend:
    image: joseluisq/static-web-server:2
    ports:
      - 8787:80
    environment:
      - SERVER_CONFIG_FILE=/config.toml
    volumes:
      - ./apps/frontend/config.toml:/config.toml
      - ./apps/frontend/dist:/public
 ```
