### DISCUSSION TITLE
How to do custom headers with multiple sources

### DISCUSSION THREAD

**Discussion by pizzapanther** [static-web-server/static-web-server#316] [Q&A] [answered]
Is there an example of how to do customer headers for different sources:

```
[advanced]

[[advanced.headers]]
source = "*.html"
[advanced.headers.headers]
Cache-Control = "public, max-age=36000"
```

Like `*.html` (see above) and then another rule say for `*.jpg` with different headers?

**Comment by joseluisq** [comment, marked as answer]
If I got it correctly, do you want multiple rules per specified source?
then just create as many `[[advanced.headers]]` (a.k.a [Toml Array of tables](https://toml.io/en/v1.0.0#array-of-tables)) as you want.

```toml
[advanced]

# rule for HTML files
[[advanced.headers]]
source = "*.html"
[advanced.headers.headers]
Cache-Control = "public, max-age=36000"

# another rule for JPEG files
[[advanced.headers]]
source = "*.jpg"
[advanced.headers.headers]
Content-Security-Policy = "frame-ancestors 'self'"

# and so on
```
