### DISCUSSION TITLE
Infinite redirect loop

### DISCUSSION THREAD

**Discussion by mschoettle** [static-web-server/static-web-server#498] [Q&A] [answered]
I have a website where I switched frameworks behind it which means that most URLs slightly changed. For example:

`/category/self-hosting/` is now `/blog/category/self-hosting/`

So I set up a redirect as follows for those categories that still exist:

```toml
[[advanced.redirects]]
source = "/category/{*}/"
destination = "/blog/category/$1/"
kind = 301
```

However, this leads to an infinite loop because `/category/foo/` redirects to `/blog/category/foo/` which redirects to `/blog/blog/categories/foo/` and so on.

Is there any way to specify to match only the full path after the hostname? An equivalent in regex would be `^/category/...`.

**Comment by joseluisq** [comment]
Your `advanced.redirects` example does not enter into a loop if you request `/category/foo`. Can you please provide a more detailed example so you can help to understand it better or a way to reproduce your issue?

**Reply by mschoettle** [reply]
You are right. Sorry, my bad. I should have done more digging and creating a minimal reproducible example before posting.

It is the combination of the following rules:

```toml
# categories that still exist
[[advanced.redirects]]
source = "/category/{*}/"
destination = "/blog/category/$1/"
kind = 301

# blog archive: month not accessible anymore
[[advanced.redirects]]
source = "/{*}/{*}/"
destination = "/blog/archive/$1/"
kind = 301

# blog posts
[[advanced.redirects]]
source = "/{*}/{*}/{*}/{*}/"
destination = "/blog/$1/$2/$3/$4/"
kind = 301
```

```output
app-1  | 2024-11-18T11:19:29.385314Z  INFO static_web_server::log_addr: incoming request: method=HEAD uri=/category/foo/
app-1  | 2024-11-18T11:19:29.385354Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern: ["$0", "$1", "$2"]
app-1  | 2024-11-18T11:19:29.385379Z DEBUG static_web_server::redirects: url redirects/rewrites regex equivalent: ^/(.*)/(.*)/$
app-1  | 2024-11-18T11:19:29.385381Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern captures: ["/category/foo/", "category", "foo"]
app-1  | 2024-11-18T11:19:29.385384Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern destination: "/blog/archive/$1/"
app-1  | 2024-11-18T11:19:29.385486Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern destination replaced: "/blog/archive/category/"
app-1  | 2024-11-18T11:19:29.385533Z DEBUG hyper::proto::h1::io: flushed 106 bytes
app-1  | 2024-11-18T11:20:07.050294Z DEBUG hyper::proto::h1::io: parsed 9 headers
app-1  | 2024-11-18T11:20:07.052225Z DEBUG hyper::proto::h1::conn: incoming body is empty
app-1  | 2024-11-18T11:20:07.052510Z  INFO static_web_server::log_addr: incoming request: method=HEAD uri=/blog/archive/category/
app-1  | 2024-11-18T11:20:07.052886Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern: ["$0", "$1", "$2"]
app-1  | 2024-11-18T11:20:07.053064Z DEBUG static_web_server::redirects: url redirects/rewrites regex equivalent: ^/(.*)/(.*)/$
app-1  | 2024-11-18T11:20:07.053245Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern captures: ["/blog/archive/category/", "blog/archive", "category"]
app-1  | 2024-11-18T11:20:07.053571Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern destination: "/blog/archive/$1/"
app-1  | 2024-11-18T11:20:07.053914Z DEBUG static_web_server::redirects: url redirects/rewrites glob pattern destination replaced: "/blog/archive/blog/archive/"
```

I've tried using `[!/]` to exclude `/` but so far I have not found a solution that works. Any regex characters get escaped into the final regex:

```output
app-1  | 2024-11-18T15:00:48.394147Z DEBUG static_web_server::settings: url redirects glob pattern: /{[!/.*]+}/{[!/.*]+}/{[!/.*]+}/{[!/.*]+}/
app-1  | 2024-11-18T15:00:48.394326Z DEBUG static_web_server::settings: url redirects regex equivalent: ^/([^/\.\*]\+)/([^/\.\*]\+)/([^/\.\*]\+)/([^/\.\*]\+)/$
```

**Reply by joseluisq** [reply]
> ```toml
> # categories that still exist
> [[advanced.redirects]]
> source = "/category/{*}/"
> destination = "/blog/category/$1/"
> kind = 301
> 
> # blog archive: month not accessible anymore
> [[advanced.redirects]]
> source = "/{*}/{*}/"
> destination = "/blog/archive/$1/"
> kind = 301
> 
> # blog posts
> [[advanced.redirects]]
> source = "/{*}/{*}/{*}/{*}/"
> destination = "/blog/$1/$2/$3/$4/"
> kind = 301
> ```

The problem is that your patterns are composed generically (E.g. `/{*}/{*}/`) which will match everything including slashes, entering in a redirect loop.
Instead, you can try `/[a-z0-9-]/[a-z0-9-]/` (be more specific) rather than `/{*}/{*}/` as Redirect's `source` and play around with combinations of this for your other Redirect entries.

Also, enable the debug logs to compare the Redirects Regex equivalent used by SWS.

**Reply by mschoettle** [reply]
Thanks. I had noticed that it gets converted into regex when enabling the debug log.

It seems to be that certain characters get escaped.

For example:

```toml
[[advanced.redirects]]
source = '/([0-9]+)/[0-9]*/'
destination = '/blog/archive/$1/'
kind = 301
```

```
2024-11-22T11:01:46.819198Z DEBUG static_web_server::settings: url redirects glob pattern: /([0-9]+)/[0-9]*/
2024-11-22T11:01:46.819205Z DEBUG static_web_server::settings: url redirects regex equivalent: ^/\([0-9]\+\)/[0-9].*/$
```

Parentheses and `+` get escaped. `*` is replaced with `.*`, and `?` is replaced with `.`.
