### DISCUSSION TITLE
traefik certresolver

### DISCUSSION THREAD

**Discussion by straight-into-the-wall** [static-web-server/static-web-server#63] [Q&A] [answered]
Hi,
I would like to use **static-web-server** with **docker-compose**, **traefik** and its **certresolver**, something like this:

```yml
...
  blogstatic:
    image: joseluisq/static-web-server:2
    container_name: "blogstatic"
    restart: always
    environment:
      - SERVER_PORT=8787
      - SERVER_ROOT=/public
      - SERVER_DIRECTORY_LISTING=true
      - SERVER_HTTP2_TLS=true
    ports:
      - "8787:443"
    volumes:
      - ./blog:/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blogstatic.rule=Host(`mysite.com`)"
      - "traefik.http.routers.blogstatic.entrypoints=websecure"
      - "traefik.http.routers.blogstatic.tls.certresolver=mysiteschallenge"
```
Is it possible?
