### ISSUE TITLE
Conditional header logic

### ISSUE THREAD

**Issue by Geobert** [static-web-server/static-web-server#500]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Completely new feature

### Feature request related to a problem

Follow up to the discussion https://github.com/orgs/static-web-server/discussions/499

### Describe the solution you'd like

To allow blocking from unwanted User-agent, it would be cool to have conditional headers logic

### Describe alternatives you've considered

none

### Build target

All targets

**Comment by YashSensei** [comment]
I'd like to work on this. Conditional header logic with User-agent-based blocking would be a solid addition.

Plan:
1. Add TOML config for conditional header rules (match on User-agent, path, method, etc.)
2. Implement the matching engine in the request pipeline
3. Support both blocking (deny) and header injection (set/append)
4. Add tests for matching logic and edge cases (empty UA, wildcard patterns, multiple conditions)

Working in a fork. Will follow existing config patterns in the codebase.

**Comment by joseluisq** [comment]
@YashSensei sure, throw your ideas out and let me know.

**Comment by YashSensei** [comment]
@joseluisq here is a concrete proposal for conditional header logic.

Goal: let users block or modify responses based on request headers like User-Agent, but keep the syntax familiar to existing SWS config.

Example TOML:

```toml
[[conditional_headers]]
name = "User-Agent"
value = "*BadBot*"
op = "glob"
kind = "deny"
status = 403
```

What each field means:
- `name`: the request header to look at
- `value`: the value or pattern to match
- `op`: `exact`, `glob`, or `regex`
- `kind`: `deny`, `allow`, or `apply` (more on apply below)
- `status`: HTTP status to return when denied, optional

Rules are checked in order. The first match wins. If no rule matches, the request continues normally.

For the `apply` kind, users can set response headers instead of blocking:

```toml
[[conditional_headers]]
name = "User-Agent"
value = "*Mobile*"
op = "glob"
kind = "apply"
headers.X-Custom-Layout = "mobile"
```

This keeps the feature general. It is not just a bot blocker. It becomes a small conditional response layer.

Where it fits in the code:
1. Add a `conditional_headers` field to the config struct.
2. Add a new handler or middleware that runs after routing but before serving the file.
3. If a deny rule matches, return the configured status early.
4. If an apply rule matches, append the configured response headers.
5. Add tests for glob, regex, exact match, and rule ordering.

I can start with a PR that implements the `deny` path first, then add `apply` in a follow-up. That keeps the first diff small and reviewable.

Does this match what you had in mind? Happy to adjust the shape before I start coding.

**Comment by dk5488** [comment]
Hey there! I'd be happy to take on adding the conditional header logic—could you assign this to me?

**Comment by joseluisq** [comment]
> [@joseluisq](https://github.com/joseluisq) here is a concrete proposal for conditional header logic.
> 
> Goal: let users block or modify responses based on request headers like User-Agent, but keep the syntax familiar to existing SWS config.
> 
> Example TOML:
> 
> [[conditional_headers]]
> name = "User-Agent"
> value = "*BadBot*"
> op = "glob"
> kind = "deny"
> status = 403
> What each field means:
> 
> * `name`: the request header to look at
> * `value`: the value or pattern to match
> * `op`: `exact`, `glob`, or `regex`
> * `kind`: `deny`, `allow`, or `apply` (more on apply below)
> * `status`: HTTP status to return when denied, optional
> 
> Rules are checked in order. The first match wins. If no rule matches, the request continues normally.
> 
> For the `apply` kind, users can set response headers instead of blocking:
> 
> [[conditional_headers]]
> name = "User-Agent"
> value = "*Mobile*"
> op = "glob"
> kind = "apply"
> headers.X-Custom-Layout = "mobile"
> This keeps the feature general. It is not just a bot blocker. It becomes a small conditional response layer.
> 
> Where it fits in the code:
> 
> 1. Add a `conditional_headers` field to the config struct.
> 2. Add a new handler or middleware that runs after routing but before serving the file.
> 3. If a deny rule matches, return the configured status early.
> 4. If an apply rule matches, append the configured response headers.
> 5. Add tests for glob, regex, exact match, and rule ordering.
> 
> I can start with a PR that implements the `deny` path first, then add `apply` in a follow-up. That keeps the first diff small and reviewable.
> 
> Does this match what you had in mind? Happy to adjust the shape before I start coding.

@YashSensei, your proposal is not bad but I should prefer to stick with `[[advanced.headers]]` and enhance it to support some way of conditionals. Also, stick with glob patterns and drop any regex usage, as glob is safer/simpler than regex and powerful enough to cover a large set of use cases.
 
Here is a prototype idea:

```toml
# 1. Request filters: pre-processing and short-circuits
[[advanced.filters]]
source  = "/**"          # optional URI path glob, default "/**"
methods = ["GET", "HEAD"]  # optional
action  = "deny"         # deny | allow | log
status  = 403            # optional, default 403

[advanced.filters.match-headers]
user-agent = ["*GPTBot*", "*ClaudeBot*", "*Bytespider*"]

# 2. Conditional response headers — extends the existing table
[[advanced.headers]]
source = "/**"
[advanced.headers.when.match-headers]
user-agent = ["*Mobile*"]
[advanced.headers.headers]
X-Layout = "mobile"
```

And as you said, this should behave as a conditional logic layer for different purposes than just blocking crawlers.

Regarding _conditional header_ support seen as "User-Agent blocker".
I do not believe that this eventual feature alone could serve as a User-Agent blocker per se because if a malicious crawler changes the header multiple times, then it could defeat user-predefined rules.
SWS should support some kind of rate limiting to act as an effective bot blocker along with conditional headers but this is something that deserves another place to propose and discuss.
